export const actions = {
	FETCH_PRODUCT: 'FETCH_PRODUCT',
	FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
	FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',
	ADD_PRODUCT: 'ADD_PRODUCT',
	ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
	ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',
};
