export const actions = {
	FETCH_USER: 'FETCH_USER',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILED: 'FETCH_USER_FAILED',

	FETCH_PRODUCT: 'FETCH_PRODUCT',
	FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
	FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',

	ADD_PRODUCT: 'ADD_PRODUCT',
	ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
	ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',

	REMOVE_PRODUCT: 'REMOVE_PRODUCT',
	REMOVE_PRODUCT_SUCCESS: 'REMOVE_PRODUCT_SUCCESS',
	REMOVE_PRODUCT_FAILED: 'REMOVE_PRODUCT_FAILED',

	EMPTY_BASKET: 'EMPTY_BASKET',
	EMPTY_BASKET_SUCCESS: 'EMPTY_BASKET_SUCCESS',
	EMPTY_BASKET_FAILED: 'EMPTY_BASKET_FAILED',
};
